server:
  port: 16000
spring:
  application:
    name: "consumer-server"
eureka:
  instance:
    prefer-ip-address: true #不加则服务器上原本是ip地址的地方会变成机器地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #该服务的ip地址 告知服务器
    lease-renewal-interval-in-seconds: 5 #5s通信一次
    lease-expiration-duration-in-seconds: 15 #15s之内没有通信则删除该服务
  client: #微服务注册中心地址
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"

resilience4j:
  circuitbreaker:
    configs:
      default:
        wait-duration-in-open-state: 10000
        event-consumer-buffer-size: 5
        record-exceptions: java.lang.Exception
        register-health-indicator: true
    instances:
      circuitbreakerA:
        base-config: default
        failure-rate-threshold: 30
        sliding-window-type: count_based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
      circuitbreakerB:
        base-config: default
        failure-rate-threshold: 50
        slow-call-rate-threshold: 30
        slow-call-duration-threshold: 2s
        sliding-window-type: count_based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3